version: '3.8'

services:
  web:
    image: nginx
    volumes:
      - ./host/static:/app/static
      - ./host/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./host/proxy/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - shared-files:/app/files:ro

    ports:
      - "80:80"
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80
    depends_on:
      - auth-service

  auth-db:
    image: postgres
    restart: always
    env_file:
      - docker/db.env
    volumes:
      - auth-db-data:/var/lib/postgresql/data
  auth-service:
    build: microservice/auth
    restart: always
    env_file:
      - docker/service/.env
      - docker/db.env
    environment:
      POSTGRES_HOST: 'auth-db'
      DB_URL: jdbc:pgsql://auth-db:5432/db
    depends_on:
      - auth-db


volumes:
  shared-files:
  auth-db-data:
    driver: local